%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.18.4 on {{2015,6,8},{17,3,32}}

-ifndef(protocol).
-define(protocol, true).

-define(protocol_gpb_version, "3.18.4").

-record('ProtocolVector2',
        {x,                             % = 1, float
         y                              % = 2, float
        }).

-record('ProtocolUnit',
        {id,                            % = 1, string
         pos,                           % = 2, {msg,'ProtocolVector2'}
         towards,                       % = 3, {msg,'ProtocolVector2'}
         status,                        % = 4, {enum,'Unit.UnitStatus'}
         score,                         % = 5, float
         name,                          % = 6, string (optional)
         color                          % = 7, int32 (optional)
        }).

-record('ProtocolUnitUpdate',
        {milliseconds,                  % = 1, int64
         units = []                     % = 2, [{msg,'ProtocolUnit'}]
        }).

-record('ProtocolDot',
        {id,                            % = 1, string
         pos,                           % = 2, {msg,'ProtocolVector2'}
         color                          % = 3, int32
        }).

-record('ProtocolDotAdd',
        {dots = []                      % = 1, [{msg,'ProtocolDot'}]
        }).

-record('ProtocolUnitAdd',
        {units = []                     % = 1, [{msg,'ProtocolUnit'}]
        }).

-record('ProtocolSceneInit',
        {unit_adds,                     % = 1, {msg,'ProtocolUnitAdd'}
         dot_adds                       % = 2, {msg,'ProtocolDotAdd'}
        }).

-record('ProtocolDotRemove',
        {ids = []                       % = 1, [string]
        }).

-record('ProtocolUnitRemove',
        {ids = []                       % = 1, [string]
        }).

-record('ProtocolSceneSync',
        {unit_updates,                  % = 1, {msg,'ProtocolUnitUpdate'}
         unit_removes,                  % = 2, {msg,'ProtocolUnitRemove'} (optional)
         dot_adds,                      % = 3, {msg,'ProtocolDotAdd'} (optional)
         dot_removes                    % = 4, {msg,'ProtocolDotRemove'} (optional)
        }).

-record('ProtocolTimeSync',
        {client,                        % = 1, int64
         server                         % = 2, int64
        }).

-endif.
