%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.18.4 on {{2015,5,27},{23,50,55}}
-module(protocol).

-export([encode_msg/1, encode_msg/2]).
-export([decode_msg/2]).
-export([merge_msgs/2]).
-export([verify_msg/1]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([get_package_name/0]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).

-include("protocol.hrl").
-include("gpb.hrl").


encode_msg(Msg) -> encode_msg(Msg, []).


encode_msg(Msg, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg);
      false -> ok
    end,
    case Msg of
      #'ProtocolUnit'{} -> e_msg_ProtocolUnit(Msg);
      #'ProtocolUnitUpdate'{} ->
	  e_msg_ProtocolUnitUpdate(Msg);
      #'ProtocolUnitAdd'{} -> e_msg_ProtocolUnitAdd(Msg);
      #'ProtocolUnitRemove'{} -> e_msg_ProtocolUnitRemove(Msg)
    end.


e_msg_ProtocolUnit(Msg) ->
    e_msg_ProtocolUnit(Msg, <<>>).


e_msg_ProtocolUnit(#'ProtocolUnit'{id = F1, pos = F2,
				   move_vector = F3, name = F4, size = F5,
				   color = F6},
		   Bin) ->
    B1 = e_type_string(F1, <<Bin/binary, 10>>),
    B2 = if F2 == [] -> B1;
	    true -> e_field_ProtocolUnit_pos(F2, B1)
	 end,
    B3 = if F3 == [] -> B2;
	    true -> e_field_ProtocolUnit_move_vector(F3, B2)
	 end,
    B4 = if F4 == undefined -> B3;
	    true -> e_type_string(F4, <<B3/binary, 34>>)
	 end,
    B5 = if F5 == undefined -> B4;
	    true -> e_type_float(F5, <<B4/binary, 45>>)
	 end,
    if F6 == undefined -> B5;
       true -> e_type_int32(F6, <<B5/binary, 48>>)
    end.

e_msg_ProtocolUnitUpdate(Msg) ->
    e_msg_ProtocolUnitUpdate(Msg, <<>>).


e_msg_ProtocolUnitUpdate(#'ProtocolUnitUpdate'{units =
						   F1},
			 Bin) ->
    if F1 == [] -> Bin;
       true -> e_field_ProtocolUnitUpdate_units(F1, Bin)
    end.

e_msg_ProtocolUnitAdd(Msg) ->
    e_msg_ProtocolUnitAdd(Msg, <<>>).


e_msg_ProtocolUnitAdd(#'ProtocolUnitAdd'{units = F1},
		      Bin) ->
    if F1 == [] -> Bin;
       true -> e_field_ProtocolUnitAdd_units(F1, Bin)
    end.

e_msg_ProtocolUnitRemove(Msg) ->
    e_msg_ProtocolUnitRemove(Msg, <<>>).


e_msg_ProtocolUnitRemove(#'ProtocolUnitRemove'{ids =
						   F1},
			 Bin) ->
    if F1 == [] -> Bin;
       true -> e_field_ProtocolUnitRemove_ids(F1, Bin)
    end.

e_field_ProtocolUnit_pos([Elem | Rest], Bin) ->
    Bin2 = <<Bin/binary, 21>>,
    Bin3 = e_type_float(Elem, Bin2),
    e_field_ProtocolUnit_pos(Rest, Bin3);
e_field_ProtocolUnit_pos([], Bin) -> Bin.

e_field_ProtocolUnit_move_vector([Elem | Rest], Bin) ->
    Bin2 = <<Bin/binary, 29>>,
    Bin3 = e_type_float(Elem, Bin2),
    e_field_ProtocolUnit_move_vector(Rest, Bin3);
e_field_ProtocolUnit_move_vector([], Bin) -> Bin.

e_mfield_ProtocolUnitUpdate_units(Msg, Bin) ->
    SubBin = e_msg_ProtocolUnit(Msg, <<>>),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_ProtocolUnitUpdate_units([Elem | Rest], Bin) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_ProtocolUnitUpdate_units(Elem, Bin2),
    e_field_ProtocolUnitUpdate_units(Rest, Bin3);
e_field_ProtocolUnitUpdate_units([], Bin) -> Bin.

e_mfield_ProtocolUnitAdd_units(Msg, Bin) ->
    SubBin = e_msg_ProtocolUnit(Msg, <<>>),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_ProtocolUnitAdd_units([Elem | Rest], Bin) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_ProtocolUnitAdd_units(Elem, Bin2),
    e_field_ProtocolUnitAdd_units(Rest, Bin3);
e_field_ProtocolUnitAdd_units([], Bin) -> Bin.

e_field_ProtocolUnitRemove_ids([Elem | Rest], Bin) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_type_string(Elem, Bin2),
    e_field_ProtocolUnitRemove_ids(Rest, Bin3);
e_field_ProtocolUnitRemove_ids([], Bin) -> Bin.

e_type_int32(Value, Bin)
    when 0 =< Value, Value =< 127 ->
    <<Bin/binary, Value>>;
e_type_int32(Value, Bin) ->
    <<N:32/unsigned-native>> = <<Value:32/signed-native>>,
    e_varint(N, Bin).

e_type_string(S, Bin) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

e_type_float(Value, Bin) ->
    <<Bin/binary, Value:32/little-float>>.

e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).



decode_msg(Bin, MsgName) when is_binary(Bin) ->
    case MsgName of
      'ProtocolUnit' -> d_msg_ProtocolUnit(Bin);
      'ProtocolUnitUpdate' -> d_msg_ProtocolUnitUpdate(Bin);
      'ProtocolUnitAdd' -> d_msg_ProtocolUnitAdd(Bin);
      'ProtocolUnitRemove' -> d_msg_ProtocolUnitRemove(Bin)
    end.



d_msg_ProtocolUnit(Bin) ->
    dfp_read_field_def_ProtocolUnit(Bin, 0, 0, undefined,
				    [], [], undefined, undefined, undefined).

dfp_read_field_def_ProtocolUnit(<<10, Rest/binary>>, Z1,
				Z2, F1, F2, F3, F4, F5, F6) ->
    d_field_ProtocolUnit_id(Rest, Z1, Z2, F1, F2, F3, F4,
			    F5, F6);
dfp_read_field_def_ProtocolUnit(<<21, Rest/binary>>, Z1,
				Z2, F1, F2, F3, F4, F5, F6) ->
    d_field_ProtocolUnit_pos(Rest, Z1, Z2, F1, F2, F3, F4,
			     F5, F6);
dfp_read_field_def_ProtocolUnit(<<29, Rest/binary>>, Z1,
				Z2, F1, F2, F3, F4, F5, F6) ->
    d_field_ProtocolUnit_move_vector(Rest, Z1, Z2, F1, F2,
				     F3, F4, F5, F6);
dfp_read_field_def_ProtocolUnit(<<34, Rest/binary>>, Z1,
				Z2, F1, F2, F3, F4, F5, F6) ->
    d_field_ProtocolUnit_name(Rest, Z1, Z2, F1, F2, F3, F4,
			      F5, F6);
dfp_read_field_def_ProtocolUnit(<<45, Rest/binary>>, Z1,
				Z2, F1, F2, F3, F4, F5, F6) ->
    d_field_ProtocolUnit_size(Rest, Z1, Z2, F1, F2, F3, F4,
			      F5, F6);
dfp_read_field_def_ProtocolUnit(<<48, Rest/binary>>, Z1,
				Z2, F1, F2, F3, F4, F5, F6) ->
    d_field_ProtocolUnit_color(Rest, Z1, Z2, F1, F2, F3, F4,
			       F5, F6);
dfp_read_field_def_ProtocolUnit(<<>>, 0, 0, F1, F2, F3,
				F4, F5, F6) ->
    #'ProtocolUnit'{id = F1, pos = lists:reverse(F2),
		    move_vector = lists:reverse(F3), name = F4, size = F5,
		    color = F6};
dfp_read_field_def_ProtocolUnit(Other, Z1, Z2, F1, F2,
				F3, F4, F5, F6) ->
    dg_read_field_def_ProtocolUnit(Other, Z1, Z2, F1, F2,
				   F3, F4, F5, F6).

dg_read_field_def_ProtocolUnit(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1, F2, F3, F4, F5, F6)
    when N < 32 - 7 ->
    dg_read_field_def_ProtocolUnit(Rest, N + 7,
				   X bsl N + Acc, F1, F2, F3, F4, F5, F6);
dg_read_field_def_ProtocolUnit(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1, F2, F3, F4, F5, F6) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_ProtocolUnit_id(Rest, 0, 0, F1, F2, F3, F4, F5,
				  F6);
      21 ->
	  d_field_ProtocolUnit_pos(Rest, 0, 0, F1, F2, F3, F4, F5,
				   F6);
      29 ->
	  d_field_ProtocolUnit_move_vector(Rest, 0, 0, F1, F2, F3,
					   F4, F5, F6);
      34 ->
	  d_field_ProtocolUnit_name(Rest, 0, 0, F1, F2, F3, F4,
				    F5, F6);
      45 ->
	  d_field_ProtocolUnit_size(Rest, 0, 0, F1, F2, F3, F4,
				    F5, F6);
      48 ->
	  d_field_ProtocolUnit_color(Rest, 0, 0, F1, F2, F3, F4,
				     F5, F6);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_ProtocolUnit(Rest, 0, 0, F1, F2, F3, F4, F5,
					 F6);
	    1 ->
		skip_64_ProtocolUnit(Rest, 0, 0, F1, F2, F3, F4, F5,
				     F6);
	    2 ->
		skip_length_delimited_ProtocolUnit(Rest, 0, 0, F1, F2,
						   F3, F4, F5, F6);
	    5 ->
		skip_32_ProtocolUnit(Rest, 0, 0, F1, F2, F3, F4, F5, F6)
	  end
    end;
dg_read_field_def_ProtocolUnit(<<>>, 0, 0, F1, F2, F3,
			       F4, F5, F6) ->
    #'ProtocolUnit'{id = F1, pos = lists:reverse(F2),
		    move_vector = lists:reverse(F3), name = F4, size = F5,
		    color = F6}.

d_field_ProtocolUnit_id(<<1:1, X:7, Rest/binary>>, N,
			Acc, F1, F2, F3, F4, F5, F6)
    when N < 57 ->
    d_field_ProtocolUnit_id(Rest, N + 7, X bsl N + Acc, F1,
			    F2, F3, F4, F5, F6);
d_field_ProtocolUnit_id(<<0:1, X:7, Rest/binary>>, N,
			Acc, _, F2, F3, F4, F5, F6) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_ProtocolUnit(Rest2, 0, 0, NewFValue,
				    F2, F3, F4, F5, F6).


d_field_ProtocolUnit_pos(<<Value:32/little-float,
			   Rest/binary>>,
			 Z1, Z2, F1, F2, F3, F4, F5, F6) ->
    dfp_read_field_def_ProtocolUnit(Rest, Z1, Z2, F1,
				    [Value | F2], F3, F4, F5, F6).


d_field_ProtocolUnit_move_vector(<<Value:32/little-float,
				   Rest/binary>>,
				 Z1, Z2, F1, F2, F3, F4, F5, F6) ->
    dfp_read_field_def_ProtocolUnit(Rest, Z1, Z2, F1, F2,
				    [Value | F3], F4, F5, F6).


d_field_ProtocolUnit_name(<<1:1, X:7, Rest/binary>>, N,
			  Acc, F1, F2, F3, F4, F5, F6)
    when N < 57 ->
    d_field_ProtocolUnit_name(Rest, N + 7, X bsl N + Acc,
			      F1, F2, F3, F4, F5, F6);
d_field_ProtocolUnit_name(<<0:1, X:7, Rest/binary>>, N,
			  Acc, F1, F2, F3, _, F5, F6) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_ProtocolUnit(Rest2, 0, 0, F1, F2, F3,
				    NewFValue, F5, F6).


d_field_ProtocolUnit_size(<<Value:32/little-float,
			    Rest/binary>>,
			  Z1, Z2, F1, F2, F3, F4, _, F6) ->
    dfp_read_field_def_ProtocolUnit(Rest, Z1, Z2, F1, F2,
				    F3, F4, Value, F6).


d_field_ProtocolUnit_color(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F1, F2, F3, F4, F5, F6)
    when N < 57 ->
    d_field_ProtocolUnit_color(Rest, N + 7, X bsl N + Acc,
			       F1, F2, F3, F4, F5, F6);
d_field_ProtocolUnit_color(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F1, F2, F3, F4, F5, _) ->
    <<NewFValue:32/signed-native>> = <<(X bsl N +
					  Acc):32/unsigned-native>>,
    dfp_read_field_def_ProtocolUnit(Rest, 0, 0, F1, F2, F3,
				    F4, F5, NewFValue).


skip_varint_ProtocolUnit(<<1:1, _:7, Rest/binary>>, Z1,
			 Z2, F1, F2, F3, F4, F5, F6) ->
    skip_varint_ProtocolUnit(Rest, Z1, Z2, F1, F2, F3, F4,
			     F5, F6);
skip_varint_ProtocolUnit(<<0:1, _:7, Rest/binary>>, Z1,
			 Z2, F1, F2, F3, F4, F5, F6) ->
    dfp_read_field_def_ProtocolUnit(Rest, Z1, Z2, F1, F2,
				    F3, F4, F5, F6).


skip_length_delimited_ProtocolUnit(<<1:1, X:7,
				     Rest/binary>>,
				   N, Acc, F1, F2, F3, F4, F5, F6)
    when N < 57 ->
    skip_length_delimited_ProtocolUnit(Rest, N + 7,
				       X bsl N + Acc, F1, F2, F3, F4, F5, F6);
skip_length_delimited_ProtocolUnit(<<0:1, X:7,
				     Rest/binary>>,
				   N, Acc, F1, F2, F3, F4, F5, F6) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_ProtocolUnit(Rest2, 0, 0, F1, F2, F3,
				    F4, F5, F6).


skip_32_ProtocolUnit(<<_:32, Rest/binary>>, Z1, Z2, F1,
		     F2, F3, F4, F5, F6) ->
    dfp_read_field_def_ProtocolUnit(Rest, Z1, Z2, F1, F2,
				    F3, F4, F5, F6).


skip_64_ProtocolUnit(<<_:64, Rest/binary>>, Z1, Z2, F1,
		     F2, F3, F4, F5, F6) ->
    dfp_read_field_def_ProtocolUnit(Rest, Z1, Z2, F1, F2,
				    F3, F4, F5, F6).


d_msg_ProtocolUnitUpdate(Bin) ->
    dfp_read_field_def_ProtocolUnitUpdate(Bin, 0, 0, []).

dfp_read_field_def_ProtocolUnitUpdate(<<10,
					Rest/binary>>,
				      Z1, Z2, F1) ->
    d_field_ProtocolUnitUpdate_units(Rest, Z1, Z2, F1);
dfp_read_field_def_ProtocolUnitUpdate(<<>>, 0, 0, F1) ->
    #'ProtocolUnitUpdate'{units = lists:reverse(F1)};
dfp_read_field_def_ProtocolUnitUpdate(Other, Z1, Z2,
				      F1) ->
    dg_read_field_def_ProtocolUnitUpdate(Other, Z1, Z2, F1).

dg_read_field_def_ProtocolUnitUpdate(<<1:1, X:7,
				       Rest/binary>>,
				     N, Acc, F1)
    when N < 32 - 7 ->
    dg_read_field_def_ProtocolUnitUpdate(Rest, N + 7,
					 X bsl N + Acc, F1);
dg_read_field_def_ProtocolUnitUpdate(<<0:1, X:7,
				       Rest/binary>>,
				     N, Acc, F1) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_ProtocolUnitUpdate_units(Rest, 0, 0, F1);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_ProtocolUnitUpdate(Rest, 0, 0, F1);
	    1 -> skip_64_ProtocolUnitUpdate(Rest, 0, 0, F1);
	    2 ->
		skip_length_delimited_ProtocolUnitUpdate(Rest, 0, 0,
							 F1);
	    5 -> skip_32_ProtocolUnitUpdate(Rest, 0, 0, F1)
	  end
    end;
dg_read_field_def_ProtocolUnitUpdate(<<>>, 0, 0, F1) ->
    #'ProtocolUnitUpdate'{units = lists:reverse(F1)}.

d_field_ProtocolUnitUpdate_units(<<1:1, X:7,
				   Rest/binary>>,
				 N, Acc, F1)
    when N < 57 ->
    d_field_ProtocolUnitUpdate_units(Rest, N + 7,
				     X bsl N + Acc, F1);
d_field_ProtocolUnitUpdate_units(<<0:1, X:7,
				   Rest/binary>>,
				 N, Acc, F1) ->
    Len = X bsl N + Acc,
    <<Bs:Len/binary, Rest2/binary>> = Rest,
    NewFValue = decode_msg(Bs, 'ProtocolUnit'),
    dfp_read_field_def_ProtocolUnitUpdate(Rest2, 0, 0,
					  [NewFValue | F1]).


skip_varint_ProtocolUnitUpdate(<<1:1, _:7,
				 Rest/binary>>,
			       Z1, Z2, F1) ->
    skip_varint_ProtocolUnitUpdate(Rest, Z1, Z2, F1);
skip_varint_ProtocolUnitUpdate(<<0:1, _:7,
				 Rest/binary>>,
			       Z1, Z2, F1) ->
    dfp_read_field_def_ProtocolUnitUpdate(Rest, Z1, Z2, F1).


skip_length_delimited_ProtocolUnitUpdate(<<1:1, X:7,
					   Rest/binary>>,
					 N, Acc, F1)
    when N < 57 ->
    skip_length_delimited_ProtocolUnitUpdate(Rest, N + 7,
					     X bsl N + Acc, F1);
skip_length_delimited_ProtocolUnitUpdate(<<0:1, X:7,
					   Rest/binary>>,
					 N, Acc, F1) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_ProtocolUnitUpdate(Rest2, 0, 0, F1).


skip_32_ProtocolUnitUpdate(<<_:32, Rest/binary>>, Z1,
			   Z2, F1) ->
    dfp_read_field_def_ProtocolUnitUpdate(Rest, Z1, Z2, F1).


skip_64_ProtocolUnitUpdate(<<_:64, Rest/binary>>, Z1,
			   Z2, F1) ->
    dfp_read_field_def_ProtocolUnitUpdate(Rest, Z1, Z2, F1).


d_msg_ProtocolUnitAdd(Bin) ->
    dfp_read_field_def_ProtocolUnitAdd(Bin, 0, 0, []).

dfp_read_field_def_ProtocolUnitAdd(<<10, Rest/binary>>,
				   Z1, Z2, F1) ->
    d_field_ProtocolUnitAdd_units(Rest, Z1, Z2, F1);
dfp_read_field_def_ProtocolUnitAdd(<<>>, 0, 0, F1) ->
    #'ProtocolUnitAdd'{units = lists:reverse(F1)};
dfp_read_field_def_ProtocolUnitAdd(Other, Z1, Z2, F1) ->
    dg_read_field_def_ProtocolUnitAdd(Other, Z1, Z2, F1).

dg_read_field_def_ProtocolUnitAdd(<<1:1, X:7,
				    Rest/binary>>,
				  N, Acc, F1)
    when N < 32 - 7 ->
    dg_read_field_def_ProtocolUnitAdd(Rest, N + 7,
				      X bsl N + Acc, F1);
dg_read_field_def_ProtocolUnitAdd(<<0:1, X:7,
				    Rest/binary>>,
				  N, Acc, F1) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_ProtocolUnitAdd_units(Rest, 0, 0, F1);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_ProtocolUnitAdd(Rest, 0, 0, F1);
	    1 -> skip_64_ProtocolUnitAdd(Rest, 0, 0, F1);
	    2 ->
		skip_length_delimited_ProtocolUnitAdd(Rest, 0, 0, F1);
	    5 -> skip_32_ProtocolUnitAdd(Rest, 0, 0, F1)
	  end
    end;
dg_read_field_def_ProtocolUnitAdd(<<>>, 0, 0, F1) ->
    #'ProtocolUnitAdd'{units = lists:reverse(F1)}.

d_field_ProtocolUnitAdd_units(<<1:1, X:7, Rest/binary>>,
			      N, Acc, F1)
    when N < 57 ->
    d_field_ProtocolUnitAdd_units(Rest, N + 7,
				  X bsl N + Acc, F1);
d_field_ProtocolUnitAdd_units(<<0:1, X:7, Rest/binary>>,
			      N, Acc, F1) ->
    Len = X bsl N + Acc,
    <<Bs:Len/binary, Rest2/binary>> = Rest,
    NewFValue = decode_msg(Bs, 'ProtocolUnit'),
    dfp_read_field_def_ProtocolUnitAdd(Rest2, 0, 0,
				       [NewFValue | F1]).


skip_varint_ProtocolUnitAdd(<<1:1, _:7, Rest/binary>>,
			    Z1, Z2, F1) ->
    skip_varint_ProtocolUnitAdd(Rest, Z1, Z2, F1);
skip_varint_ProtocolUnitAdd(<<0:1, _:7, Rest/binary>>,
			    Z1, Z2, F1) ->
    dfp_read_field_def_ProtocolUnitAdd(Rest, Z1, Z2, F1).


skip_length_delimited_ProtocolUnitAdd(<<1:1, X:7,
					Rest/binary>>,
				      N, Acc, F1)
    when N < 57 ->
    skip_length_delimited_ProtocolUnitAdd(Rest, N + 7,
					  X bsl N + Acc, F1);
skip_length_delimited_ProtocolUnitAdd(<<0:1, X:7,
					Rest/binary>>,
				      N, Acc, F1) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_ProtocolUnitAdd(Rest2, 0, 0, F1).


skip_32_ProtocolUnitAdd(<<_:32, Rest/binary>>, Z1, Z2,
			F1) ->
    dfp_read_field_def_ProtocolUnitAdd(Rest, Z1, Z2, F1).


skip_64_ProtocolUnitAdd(<<_:64, Rest/binary>>, Z1, Z2,
			F1) ->
    dfp_read_field_def_ProtocolUnitAdd(Rest, Z1, Z2, F1).


d_msg_ProtocolUnitRemove(Bin) ->
    dfp_read_field_def_ProtocolUnitRemove(Bin, 0, 0, []).

dfp_read_field_def_ProtocolUnitRemove(<<10,
					Rest/binary>>,
				      Z1, Z2, F1) ->
    d_field_ProtocolUnitRemove_ids(Rest, Z1, Z2, F1);
dfp_read_field_def_ProtocolUnitRemove(<<>>, 0, 0, F1) ->
    #'ProtocolUnitRemove'{ids = lists:reverse(F1)};
dfp_read_field_def_ProtocolUnitRemove(Other, Z1, Z2,
				      F1) ->
    dg_read_field_def_ProtocolUnitRemove(Other, Z1, Z2, F1).

dg_read_field_def_ProtocolUnitRemove(<<1:1, X:7,
				       Rest/binary>>,
				     N, Acc, F1)
    when N < 32 - 7 ->
    dg_read_field_def_ProtocolUnitRemove(Rest, N + 7,
					 X bsl N + Acc, F1);
dg_read_field_def_ProtocolUnitRemove(<<0:1, X:7,
				       Rest/binary>>,
				     N, Acc, F1) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_ProtocolUnitRemove_ids(Rest, 0, 0, F1);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_ProtocolUnitRemove(Rest, 0, 0, F1);
	    1 -> skip_64_ProtocolUnitRemove(Rest, 0, 0, F1);
	    2 ->
		skip_length_delimited_ProtocolUnitRemove(Rest, 0, 0,
							 F1);
	    5 -> skip_32_ProtocolUnitRemove(Rest, 0, 0, F1)
	  end
    end;
dg_read_field_def_ProtocolUnitRemove(<<>>, 0, 0, F1) ->
    #'ProtocolUnitRemove'{ids = lists:reverse(F1)}.

d_field_ProtocolUnitRemove_ids(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1)
    when N < 57 ->
    d_field_ProtocolUnitRemove_ids(Rest, N + 7,
				   X bsl N + Acc, F1);
d_field_ProtocolUnitRemove_ids(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_ProtocolUnitRemove(Rest2, 0, 0,
					  [NewFValue | F1]).


skip_varint_ProtocolUnitRemove(<<1:1, _:7,
				 Rest/binary>>,
			       Z1, Z2, F1) ->
    skip_varint_ProtocolUnitRemove(Rest, Z1, Z2, F1);
skip_varint_ProtocolUnitRemove(<<0:1, _:7,
				 Rest/binary>>,
			       Z1, Z2, F1) ->
    dfp_read_field_def_ProtocolUnitRemove(Rest, Z1, Z2, F1).


skip_length_delimited_ProtocolUnitRemove(<<1:1, X:7,
					   Rest/binary>>,
					 N, Acc, F1)
    when N < 57 ->
    skip_length_delimited_ProtocolUnitRemove(Rest, N + 7,
					     X bsl N + Acc, F1);
skip_length_delimited_ProtocolUnitRemove(<<0:1, X:7,
					   Rest/binary>>,
					 N, Acc, F1) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_ProtocolUnitRemove(Rest2, 0, 0, F1).


skip_32_ProtocolUnitRemove(<<_:32, Rest/binary>>, Z1,
			   Z2, F1) ->
    dfp_read_field_def_ProtocolUnitRemove(Rest, Z1, Z2, F1).


skip_64_ProtocolUnitRemove(<<_:64, Rest/binary>>, Z1,
			   Z2, F1) ->
    dfp_read_field_def_ProtocolUnitRemove(Rest, Z1, Z2, F1).




merge_msgs(Prev, New)
    when element(1, Prev) =:= element(1, New) ->
    case Prev of
      #'ProtocolUnit'{} -> merge_msg_ProtocolUnit(Prev, New);
      #'ProtocolUnitUpdate'{} ->
	  merge_msg_ProtocolUnitUpdate(Prev, New);
      #'ProtocolUnitAdd'{} ->
	  merge_msg_ProtocolUnitAdd(Prev, New);
      #'ProtocolUnitRemove'{} ->
	  merge_msg_ProtocolUnitRemove(Prev, New)
    end.

merge_msg_ProtocolUnit(#'ProtocolUnit'{id = PFid,
				       pos = PFpos, move_vector = PFmove_vector,
				       name = PFname, size = PFsize,
				       color = PFcolor},
		       #'ProtocolUnit'{id = NFid, pos = NFpos,
				       move_vector = NFmove_vector,
				       name = NFname, size = NFsize,
				       color = NFcolor}) ->
    #'ProtocolUnit'{id =
			if NFid =:= undefined -> PFid;
			   true -> NFid
			end,
		    pos = PFpos ++ NFpos,
		    move_vector = PFmove_vector ++ NFmove_vector,
		    name =
			if NFname =:= undefined -> PFname;
			   true -> NFname
			end,
		    size =
			if NFsize =:= undefined -> PFsize;
			   true -> NFsize
			end,
		    color =
			if NFcolor =:= undefined -> PFcolor;
			   true -> NFcolor
			end}.

merge_msg_ProtocolUnitUpdate(#'ProtocolUnitUpdate'{units
						       = PFunits},
			     #'ProtocolUnitUpdate'{units = NFunits}) ->
    #'ProtocolUnitUpdate'{units = PFunits ++ NFunits}.

merge_msg_ProtocolUnitAdd(#'ProtocolUnitAdd'{units =
						 PFunits},
			  #'ProtocolUnitAdd'{units = NFunits}) ->
    #'ProtocolUnitAdd'{units = PFunits ++ NFunits}.

merge_msg_ProtocolUnitRemove(#'ProtocolUnitRemove'{ids =
						       PFids},
			     #'ProtocolUnitRemove'{ids = NFids}) ->
    #'ProtocolUnitRemove'{ids = PFids ++ NFids}.



verify_msg(Msg) ->
    case Msg of
      #'ProtocolUnit'{} ->
	  v_msg_ProtocolUnit(Msg, ['ProtocolUnit']);
      #'ProtocolUnitUpdate'{} ->
	  v_msg_ProtocolUnitUpdate(Msg, ['ProtocolUnitUpdate']);
      #'ProtocolUnitAdd'{} ->
	  v_msg_ProtocolUnitAdd(Msg, ['ProtocolUnitAdd']);
      #'ProtocolUnitRemove'{} ->
	  v_msg_ProtocolUnitRemove(Msg, ['ProtocolUnitRemove']);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


v_msg_ProtocolUnit(#'ProtocolUnit'{id = F1, pos = F2,
				   move_vector = F3, name = F4, size = F5,
				   color = F6},
		   Path) ->
    v_type_string(F1, [id | Path]),
    if is_list(F2) ->
	   [v_type_float(Elem, [pos | Path]) || Elem <- F2];
       true ->
	   mk_type_error({invalid_list_of, float}, F2, Path)
    end,
    if is_list(F3) ->
	   [v_type_float(Elem, [move_vector | Path])
	    || Elem <- F3];
       true ->
	   mk_type_error({invalid_list_of, float}, F3, Path)
    end,
    if F4 == undefined -> ok;
       true -> v_type_string(F4, [name | Path])
    end,
    if F5 == undefined -> ok;
       true -> v_type_float(F5, [size | Path])
    end,
    if F6 == undefined -> ok;
       true -> v_type_int32(F6, [color | Path])
    end,
    ok;
v_msg_ProtocolUnit(X, Path) ->
    mk_type_error({expected_msg, 'ProtocolUnit'}, X, Path).

v_msg_ProtocolUnitUpdate(#'ProtocolUnitUpdate'{units =
						   F1},
			 Path) ->
    if is_list(F1) ->
	   [v_msg_ProtocolUnit(Elem, [units | Path])
	    || Elem <- F1];
       true ->
	   mk_type_error({invalid_list_of, {msg, 'ProtocolUnit'}},
			 F1, Path)
    end,
    ok.

v_msg_ProtocolUnitAdd(#'ProtocolUnitAdd'{units = F1},
		      Path) ->
    if is_list(F1) ->
	   [v_msg_ProtocolUnit(Elem, [units | Path])
	    || Elem <- F1];
       true ->
	   mk_type_error({invalid_list_of, {msg, 'ProtocolUnit'}},
			 F1, Path)
    end,
    ok.

v_msg_ProtocolUnitRemove(#'ProtocolUnitRemove'{ids =
						   F1},
			 Path) ->
    if is_list(F1) ->
	   [v_type_string(Elem, [ids | Path]) || Elem <- F1];
       true ->
	   mk_type_error({invalid_list_of, string}, F1, Path)
    end,
    ok.

v_type_int32(N, _Path)
    when -2147483648 =< N, N =< 2147483647 ->
    ok;
v_type_int32(N, Path) when is_integer(N) ->
    mk_type_error({value_out_of_range, int32, signed, 32},
		  N, Path);
v_type_int32(X, Path) ->
    mk_type_error({bad_integer, int32, signed, 32}, X,
		  Path).

v_type_float(N, _Path) when is_float(N) -> ok;
v_type_float(N, _Path) when is_integer(N) -> ok;
v_type_float(X, Path) ->
    mk_type_error(bad_float_value, X, Path).

v_type_string(S, Path) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} ->
	  mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg ->
	  mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path) ->
    mk_type_error(bad_unicode_string, X, Path).

mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error,
		  {Error, [{value, ValueSeen}, {path, Path2}]}}).


prettify_path([]) -> top_level;
prettify_path(PathR) ->
    list_to_atom(string:join(lists:map(fun atom_to_list/1,
				       lists:reverse(PathR)),
			     ".")).



get_msg_defs() ->
    [{{msg, 'ProtocolUnit'},
      [#field{name = id, fnum = 1, rnum = 2, type = string,
	      occurrence = required, opts = []},
       #field{name = pos, fnum = 2, rnum = 3, type = float,
	      occurrence = repeated, opts = []},
       #field{name = move_vector, fnum = 3, rnum = 4,
	      type = float, occurrence = repeated, opts = []},
       #field{name = name, fnum = 4, rnum = 5, type = string,
	      occurrence = optional, opts = []},
       #field{name = size, fnum = 5, rnum = 6, type = float,
	      occurrence = optional, opts = []},
       #field{name = color, fnum = 6, rnum = 7, type = int32,
	      occurrence = optional, opts = []}]},
     {{msg, 'ProtocolUnitUpdate'},
      [#field{name = units, fnum = 1, rnum = 2,
	      type = {msg, 'ProtocolUnit'}, occurrence = repeated,
	      opts = []}]},
     {{msg, 'ProtocolUnitAdd'},
      [#field{name = units, fnum = 1, rnum = 2,
	      type = {msg, 'ProtocolUnit'}, occurrence = repeated,
	      opts = []}]},
     {{msg, 'ProtocolUnitRemove'},
      [#field{name = ids, fnum = 1, rnum = 2, type = string,
	      occurrence = repeated, opts = []}]}].


get_msg_names() ->
    ['ProtocolUnit', 'ProtocolUnitUpdate',
     'ProtocolUnitAdd', 'ProtocolUnitRemove'].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


fetch_enum_def(EnumName) ->
    erlang:error({no_such_enum, EnumName}).


find_msg_def('ProtocolUnit') ->
    [#field{name = id, fnum = 1, rnum = 2, type = string,
	    occurrence = required, opts = []},
     #field{name = pos, fnum = 2, rnum = 3, type = float,
	    occurrence = repeated, opts = []},
     #field{name = move_vector, fnum = 3, rnum = 4,
	    type = float, occurrence = repeated, opts = []},
     #field{name = name, fnum = 4, rnum = 5, type = string,
	    occurrence = optional, opts = []},
     #field{name = size, fnum = 5, rnum = 6, type = float,
	    occurrence = optional, opts = []},
     #field{name = color, fnum = 6, rnum = 7, type = int32,
	    occurrence = optional, opts = []}];
find_msg_def('ProtocolUnitUpdate') ->
    [#field{name = units, fnum = 1, rnum = 2,
	    type = {msg, 'ProtocolUnit'}, occurrence = repeated,
	    opts = []}];
find_msg_def('ProtocolUnitAdd') ->
    [#field{name = units, fnum = 1, rnum = 2,
	    type = {msg, 'ProtocolUnit'}, occurrence = repeated,
	    opts = []}];
find_msg_def('ProtocolUnitRemove') ->
    [#field{name = ids, fnum = 1, rnum = 2, type = string,
	    occurrence = repeated, opts = []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


enum_symbol_by_value(E, V) ->
    erlang:error({no_enum_defs, E, V}).


enum_value_by_symbol(E, V) ->
    erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



fetch_rpc_def(ServiceName, RpcName) ->
    erlang:error({no_such_rpc, ServiceName, RpcName}).


get_package_name() -> undefined.



gpb_version_as_string() ->
    "3.18.4".

gpb_version_as_list() ->
    [3,18,4].
